### PR TITLE
Fixes/restore gridlength when visibile changes

### PR DESCRIPTION
**Pull request by danwalmsley**

### CODE REVIEW

**Comment by danwalmsley** [comment]
Ok I have fully tested this. This actually works now.

all visible
image

then restores to this:
image

**Comment by danwalmsley** [comment]
Notice the second screenshot above, there is a double thickness between solution explorer... that's because the grid splitter wasn't hidden when you don't have both items in the branch visible. Added a commit to this pr to fix it.

**Comment by danwalmsley** [comment]
image

**Comment by Seeker1437** [comment]
Nice!

**Pull request merged**
